# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nvYZX2gT-47G2fc_uiSqy7gsq33IlTE
"""

import random

import string

superset=string.ascii_letters + string.ascii_lowercase +string.ascii_uppercase +'0123456789' + "!@##$%^&*()_+-="
print(superset)

superset=string.ascii_letters + string.ascii_lowercase +string.ascii_uppercase +'0123456789' + "!@##$%^&*()_+-="
a=[0,0,0,0]
password=""
count=0
while(0 in a):
  c=(random.sample(superset,1))[0]
  if(c.isupper()==1):
    if(a[0]>4):
      continue
    password+=str(c)
    count+=1
    a[0]+=1
  elif(c.islower()==1):
    if(a[1]>4):
      continue
    password+=str(c)
    count+=1
    a[1]+=1
  elif(c.isdigit()==1):
    if(a[2]>4):
      continue
    password+=str(c)
    count+=1
    a[2]+=1
  else:
    if(a[3]>4):
      continue
    password+=str(c)
    count+=1
    a[3]+=1
print(password)